apiVersion: v1
kind: PersistentVolume
metadata:
  name: secrets-store-inline
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/secrets-store
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secrets-store-inline
  labels:
    type: code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
